# config context path to "/" by setting an empty string

crm:
  name: Smorenburg CRM

jwt:
  header: Authorization
  secret: mySecret
  expiration: 10
  routes:
    adminendpoint: admin
    apiendpoint: api
    authentication:
      authendpoint: auth
      refreshendpoint: refresh

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true